[package]
name = "tui-textarea"
version = "0.2.0"
edition = "2021"
rust-version = "1.56.1"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = """
tui-textarea is a simple yet powerful text editor widget for tui-rs and ratatui. Multi-line
text editor can be easily put as part of your TUI application.
"""
license = "MIT"
homepage = "https://github.com/rhysd/tui-textarea#readme"
repository = "https://github.com/rhysd/tui-textarea"
readme = "README.md"
categories = ["text-editors", "text-processing"]
keywords = ["tui", "textarea", "editor", "input", "edit", "ratatui"]
include = ["/src", "/examples", "/README.md", "/LICENSE.txt"]

[features]
default = ["crossterm"]
# Features to use tui-rs
crossterm = ["dep:crossterm", "ratatui/crossterm"]
termion = ["dep:termion", "ratatui/termion"]
your-backend = ["ratatui"]
# Other optional features
search = ["dep:regex"]

[dependencies]
crossterm = { package = "crossterm", version = "0.27.0", optional = true }
regex = { version = "1", optional = true }
termion = { version = "1.5", optional = true }
tui = { version = "0.19", default-features = false, optional = true }
arbitrary = { version = "1", features = ["derive"], optional = true }
ratatui = { version = "0.23.0", default-features = false, optional = true }

[workspace]
members = ["bench"]

[profile.bench]
lto = "thin"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
